config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :playgrounds do
    resources :participations
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :playground

  def update_status
    if start_date < Time.now && end_date > Time.now
      status = "ongoing"
    elsif start_date < Time.now && end_date < Time.now
      status = "coming"
    elsif start_date > Time.now && end_date > Time.now
      status = "finished"
    end
    self.update!(status: status)
  end
end

app/models/playground.rb
class Playground < ApplicationRecord
  geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?

  has_many :participations, dependent: :destroy
  validates :name, uniqueness: true

  def self.search(city)
    if city.nil?
      Playground.all
    else
      if city.respond_to?(:to_str)
        where(city: city.downcase)
      else
        where(city: city.join.downcase)
      end
    end
  end

  def current_participations_count
    participations.where(status: "ongoing").count
  end

  def coming_participations_count
    participations.where("start_date > NOW() and start_date < (NOW() + INTERVAL '1 DAY')").count
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :participations

validates :email, uniqueness: true
validates :nickname, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname, :email])


    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/pages_controller.rb
require_relative '../../db/top_cities'

class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  layout false


  def home
    @cities = TOP_CITIES.sort
  end

end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def create
    @playground = Playground.find(params[:playground_id])
    @participation = Participation.new(participation_params)
    @participation.user = current_user
    @participation.playground = @playground
    if @participation.save
      flash[:notice] = "Participation registered"
      redirect_back(fallback_location: root_path)
    end
  end


  private

  def participation_params
    params.require(:participation).permit(:start_date, :end_date, :status)
  end
end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController
  def index
    @playgrounds = Playground.search(params[:city])
    async_rake('update_stuff:participations', options = {})
    if @playgrounds.empty?
      redirect_to new_playground_path, notice: "Be the first to add a Playground in #{params[:city][0]} "
    end
     @markers = @playgrounds.map do |playground|
      {
        lat: playground.latitude,
        lng: playground.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { playground: playground })
      }
      end
  end

  def show
    @playground = Playground.find(params[:id])
    @user = current_user
    @participation = Participation.new
    @participations = @playground.participations.includes(:user).sort_by(&:start_date).reverse
  end

  def new
    @playground = Playground.new
  end

  def create
    @playground = Playground.new(playground_params)
    if @playground.save
      redirect_to playgrounds_path
    else
      render :new
    end
  end

  private

  def playground_params
    params.require(:playground).permit(:name, :address, :rims_number, :playgound_picture, :term)
  end

  def async_rake(task, options = {})
    options[:rails_env] ||= Rails.env

    # format the options as unix environmental variables
    env_vars = options.map { |key, value| "#{key.to_s.upcase}='#{value.to_s}'" }
    env_vars_string = env_vars.join(' ')

    log_file = File.join(Rails.root, "log/async_rake.#{Rails.env}.log")

    # fire and forget
    Process.fork {
      exec("#{env_vars_string} bin/rake #{task} --trace 2>&1 >> #{log_file}")
    }
    # or:
    # system("#{env_vars_string} bin/rake #{task} --trace 2>&1 >> #{log_file} &")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playground - find your basketball mates</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
      <%= yield %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playground - find your basketball mates</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/places.js@1.16.4"></script>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>




    <div class="homepage-bloc">
    <div class="titles">
      <h1 id="main-title">Playgroundz</h1>

      <h2 id="subtitle">Do not play alone!</h2>

      <%= form_tag(playgrounds_path, method: :get) do %>
          <%= select :city, params[:city], Playground.pluck(:city).uniq.compact.sort.map {|city| city.capitalize}, {prompt: 'Select a city'}, class: "select2" %>
          <%= submit_tag 'Play', city: nil, class: "btn btn-primary" %>
      <% end %>
    </div>


  </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/playgrounds/_infowindow.html.erb
<%= playground.name %>

app/views/playgrounds/index.html.erb
<h1>All playgrounds</h1>

<div class="grid-wrapper-all">

  <div class="grid-wrapper-playgrounds">
    <% @playgrounds.each do |playground| %>
      <div class="card-playground">
        <div class="playground-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1520640292646-2c3753cf3ae4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2102&q=80)">
        </div>
        <div class="playground-info">
          <div class="title-address">
            <div class="playground-name">
              <%= playground.name %>
            </div>
            <div class="playground-address">
              <%= playground.address %>
            </div>
          </div>
          <div class="player-participation">
            <%= render partial: "shared/nearby_participations", locals: {playground: playground} %>
          </div>
          <div class="join-playground">
            <%= link_to 'Join', playground_path(playground) %>
          </div>
        </div>
      </div>
    <% end %>
    <%= link_to 'Add a playground', new_playground_path %>
  </div>

  <div
    id="map"
    style="width: 50%;
    height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>

</div>

app/views/playgrounds/new.html.erb
<div class="container">
  <h1>Add a playground</h1>
    <div class="form">

    <%= simple_form_for @playground do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <%= f.input :name,
                  class: "form-control form-text text-muted"%>
      <%= f.input :address,
                  class: "form-control form-text text-muted" %>
      <%= f.input :city,
                  class: "form-control form-text text-muted"%>
      <%= f.input :rims_number,
                  class: "form-control form-text text-muted" %>
      <%= f.input :playground_picture,
                  class: "form-control form-text text-muted" %>

      <%= f.button :submit, class: "btn btn-primary"  %>
    <% end %>
    </div>
    <hr>
    <%= link_to 'Back', playgrounds_path %>
</div>

app/views/playgrounds/show.html.erb
<div class="playground-title">
  <%= @playground.name %> -
  <%= @playground.address %>
</div>

<div class="playground-join">

  <div class="date-form">
    <span>Join the playground</span>
    <%= simple_form_for [@playground, @participation] do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <%= f.input :start_date,
                  class: "form-control form-text text-muted",
                  as: :date,
                  html5: true,
                  input_html: {id: "playground-date"} %>
      <%= f.input :end_date,
                  class: "form-control form-text text-muted",
                  as: :date,
                  html5: true,
                  input_html: {id: "playground-date"}  %>
      <%= f.button :submit, class: "btn btn-primary"  %>
    <% end %>
  </div>

  <div class="playground-players">
    <span>They already play!</span>
    <%= Time.now %>
    <div class="col">
      <div class="messagebox">
        <% if @participations.present? %>
          <% @participations.each do |participation| %>
            <ul class="list-inline">
              <li class="list-inline-item"><%= participation.user.nickname  %></li>
              <li class="list-inline-item">Start on :<%= participation.start_date.strftime('%m/%d/%Y %H:%M:%S')  %></li>
              <li class="list-inline-item">End on :<%= participation.end_date.strftime('%m/%d/%Y %H:%M:%S')  %></li>
              <li class="list-inline-item"><%= participation.status  %></li>
            </ul>
          <% end %>

        <% else %>
            <p>No participants yet</p>
        <% end %>
      </div>
    </div>
  </div>

</div>

<div class="back-link">
  <%= link_to "Back to #{@playground.city}", playgrounds_path(params.merge(city: @playground.city).permit(:city)) %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "HOME", root_path, class: "navbar-brand" %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3992.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_nearby_participations.html.erb
<li class="badge badge-pill badge-primary"><%= playground.current_participations_count %> players now</li>
<li class="badge badge-pill badge-secondary"><%= playground.coming_participations_count %> playing soon</li>